name: weather
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  lottie: ^3.1.2
  flutter_spinkit: ^5.2.1
  flutter_weather_bg_null_safety: ^1.0.0
  intl: ^0.19.0
  sidebarx: ^0.17.1
  permission_handler: ^11.3.1
  location: ^6.0.2
  auto_size_text: ^3.0.0
  http: ^1.2.1

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  assets:
    - assets/anim/
    - assets/icon/

